on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production


jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: "echo 'Job: ${{github.job}} - Environment: ${{ inputs.environment }}'"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - run: "echo 'Job: ${{github.job}} - Environment: ${{ inputs.environment }}'"


  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - run: "echo 'Job: ${{github.job}} - Environment: ${{ inputs.environment }}'"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2,job_3]
    steps:
    - run: "echo 'Job: ${{github.job}} - Environment: ${{ inputs.environment }}'"

  
