name: Push and PR

on:
  push:
    branches:
      - master
      - dev/**
    paths:
      - src/**
      - .github/workflows/push-pr.yml
  pull_request:
    branches:
      - master
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: |
          uv sync --dev
          uv add ultralytics supervision opencv-python
          uv add ruff black pytest --dev

      - name: Run linting
        run: |
          uv run ruff check src/ --exclude=src/training_notebooks/
          uv run black --check src/ --exclude=src/training_notebooks/
      
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            uv run pytest tests/ -v
          else
            echo "No tests directory found - skipping tests"
          fi
